on:
  release:
      types:
         - published 

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - uses: zhanghongtong/upload-release-asset@v1
      with:
        repo: test-trello
        path: ./*
        token: ${{ secrets.AccessToken }}

